baseURL = "https://artemantohin88-lang.github.io/jagiello-blog/"
languageCode = "ru"
title = "Артём Ягелло"
theme = "jagiello"
contentDir = "content"

[taxonomies]
  category = "categories"
  tag = "tags"